{{- if .Values.oauth2.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kitapp.oauth2.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kitapp.labels" . | nindent 4 }}
data:
  oauth2-proxy.cfg: |
    {{- include "kitapp.oauth2.stableConfigToml" . | trim | nindent 4 }}
  {{- if .Values.oauth2.useAlphaConfig }}
  oauth2-proxy-alpha.yaml: |
    {{- toYaml (.Values.oauth2.alphaConfig | default dict) | nindent 4 }}
  {{- end }}
{{- end }}
