{{- if and .Values.oauth2.enabled .Values.oauth2.realm (not .Values.oauth2.existingSecret) .Values.oauth2.provisionClient }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kitapp.oauth2.secretRef" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kitapp.labels" . | nindent 4 }}
  annotations:
    argo.kitkube.dk/ignore-diff: "true"
type: Opaque
data:
  {{- include "kitapp.oauth2.secretData" . | nindent 2 }}
{{- end }}
