{{- if and .Values.oauth2.enabled (not .Values.oauth2.clientId) -}}
{{- fail "values.oauth2.clientId is required when oauth2.enabled=true" -}}
{{- end -}}
{{- if and .Values.oauth2.enabled (not .Values.oauth2.issuerUrl) -}}
{{- fail "values.oauth2.issuerUrl is required when oauth2.enabled=true" -}}
{{- end -}}
{{- if and .Values.oauth2.enabled (not .Values.oauth2.secretRef) -}}
{{- fail "values.oauth2.secretRef is required when oauth2.enabled=true" -}}
{{- end -}}
