{{- include "kitapp.validate.requiredImage" . -}}
{{- include "kitapp.validate.requiredApplicationPort" . -}}
{{- include "kitapp.validate.portNumbers" . -}}
{{- include "kitapp.validate.portNames" . -}}
{{- include "kitapp.validate.envNames" . -}}
{{- include "kitapp.validate.oauth2" . -}}
