image:
  repository: docker.io/mccutchen/go-httpbin
  tag: "v2.23.0"

applicationPort:
  name: http
  port: 8080

envFrom:
  - secretRef:
      name: my-app-secrets
      optional: true

extraEnvFrom:
  - configMapRef:
      name: my-app-config
      optional: true

startupProbe:
  httpGet:
    path: /
    port: http
  failureThreshold: 30
  periodSeconds: 10

tolerations:
  - key: dedicated
    operator: Equal
    value: app
    effect: NoSchedule

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 50
        preference:
          matchExpressions:
            - key: node-role
              operator: In
              values:
                - application
