image:
  repository: nginx
  tag: "1.31.0"

applicationPort:
  name: http
  port: 8000

gateway:
  enabled: true
  hostnames:
    - app.local
  gateway:
    name: ingressgateway
    namespace: istio-ingress
  clusterIssuer: letsencrypt-prod-istio
