image:
  repository: docker.io/mccutchen/go-httpbin
  tag: "2.23.0"

applicationPort:
  port: 8080

route:
  enabled: true
  hostnames:
    - app.example.com

oauth2:
  enabled: true
  realm: my-realm
  clientId: my-app
  issuerUrl: https://keycloak.example.com
  provisionClient: true
