image:
  repository: docker.io/mccutchen/go-httpbin
  tag: "v2.23.0"

applicationPort:
  name: http
  port: 8080

servicePort:
  port: 8080

oauth2:
  enabled: true
  secretRef: my-app-oauth2-proxy-envs
  clientId: portal
  issuerUrl: https://issuer.example.com/realms/portal

route:
  enabled: true
  hostnames:
    - my-app.example.com
  gateway:
    name: ingressgateway
    namespace: istio-ingress
  clusterIssuer: letsencrypt-prod-istio
