image:
  repository: docker.io/mccutchen/go-httpbin
  tag: "2.23.0"

applicationPort:
  name: http
  port: 8080

servicePort:
  port: 8080

oauth2:
  enabled: true
  existingSecret: my-app-oauth2-proxy-envs
  image: ghcr.io/oauth2-proxy/oauth2-proxy:v7.15.0
  clientId: my-app
  issuerUrl: https://keycloak.example.com
  realm: my-realm
  config:
    emailDomains:
      - example.com
    allowedGroups:
      - admins
    skipAuthRoutes:
      - ^/healthz$
  sidecar:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi
  providerCA:
    configMap: oidc-provider-ca
    key: ca.crt

route:
  enabled: true
  hostnames:
    - my-app.example.com
