image:
  repository: docker.io/mccutchen/go-httpbin
  tag: "2.23.0"

applicationPort:
  name: http
  port: 8080

servicePort:
  port: 8080

oauth2:
  enabled: true
  # Remember to create the referenced secret `my-app-oauth2-proxy-envs`
  # with the necessary environment variables (e.g. OAUTH2_PROXY_CLIENT_SECRET and OAUTH2_PROXY_COOKIE_SECRET) for oauth2-proxy to function.
  existingSecret: my-app-oauth2-proxy-envs
  clientId: my-app
  issuerUrl: https://keycloak.example.com
  realm: my-realm

route:
  enabled: true
  hostnames:
    - my-app.example.com
