image:
  repository: docker.io/mccutchen/go-httpbin
  tag: "v2.15.0"

applicationPort:
  port: 8080

volumes:
  - name: app-data
    mountPath: /data
    volumeSpec:
      persistentVolumeClaim:
        create: true
        accessMode: ReadWriteOnce
        size: 1Gi
  - name: app-config-file
    mountPath: /tmp/application.yaml
    subPath: application.yaml
    volumeSpec:
      emptyDir: {}
  - name: app-cache
    mountPath: /cache
    volumeSpec:
      emptyDir: {}
  - name: app-data-created
    mountPath: /created
    volumeSpec:
      persistentVolumeClaim:
        create: true
        accessMode: ReadWriteOnce
        size: 1Gi
