image:
  repository: nginx
  tag: "1.31.0"

applicationPort:
  port: 80

volumes:
  - name: app-data
    mountPath: /data
    volumeSpec:
      persistentVolumeClaim:
        existingClaim: my-existing-pvc
  - name: app-cache
    mountPath: /cache
    volumeSpec:
      emptyDir: {}
  - name: app-data-created
    mountPath: /created
    volumeSpec:
      persistentVolumeClaim:
        create: true
        size: 1Gi
