image:
  repository: docker.io/mccutchen/go-httpbin
  tag: "v2.15.0"

applicationPort:
  port: 8080

volumes:
  - name: app-data
    mountPath: /data
    volumeSpec:
      persistentVolumeClaim:
        existingClaim: my-existing-pvc
  - name: app-config-file
    mountPath: /tmp/application.yaml
    subPath: application.yaml
    volumeSpec:
      configMap:
        name: app-config
        items:
          - key: application.yaml
            path: application.yaml
  - name: app-cache
    mountPath: /cache
    volumeSpec:
      emptyDir: {}
  - name: app-data-created
    mountPath: /created
    volumeSpec:
      persistentVolumeClaim:
        create: true
        accessMode: ReadWriteOnce
        size: 1Gi

templates:
  resources:
    my-existing-pvc:
      apiVersion: v1
      kind: PersistentVolumeClaim
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
    app-config:
      apiVersion: v1
      kind: ConfigMap
      data:
        application.yaml: |
          example: true
