image:
  repository: docker.io/mccutchen/go-httpbin
  tag: "v2.23.0"

applicationPort:
  name: http
  port: 8080

serviceAccount:
  create: true
  annotations:
    this-is-a-key: this-is-a-value

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65534
  runAsGroup: 65534
  fsGroup: 65534

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault
